### ISSUE TITLE
displaying max temp in heat protection

### ISSUE THREAD

**Issue by AaronAkane** [davidwernhart/AlDente-Pro-Bug-Tracking#14]
you can set the max temperature for heat protection but every time you go back to the charge settings tab from another tab within the application it will display the max temp as "..." instead of "set temp eg:75" but upon clicking max temp square it changes from "..." to displaying correct max temp setting under heat protection in the charge settings tab. it only happens once you click out of that tab within the app

**Comment by davidwernhart** [comment]
Hey Aaron,

thank you for your feedback!
I sadly cannot reproduce that behaviour, but it seems like a regular SwiftUI scaling problem, which can depend on the type of monitor you use. I will make that textbox a little bigger in upcoming versions so that problem will hopefully not occur anymore.

Kind regards,
David
