### ISSUE TITLE
Feature request include battery health and other data from ioreg

### ISSUE THREAD

**Issue by mikebore** [davidwernhart/AlDente-Pro-Bug-Tracking#6]
Would be great if all the battery data available from ioreg and other apps (Coconut, Better Battery 2 etc) could be included in AlDente.

**Comment by MatthiasKerbl** [comment]
Hi @mikebore,

thanks for your feedback. This is on our list for potential future updates.

**Comment by julienbdx** [comment]
Hi!
In the same way, it would be great if AlDente could keep history of battery informations : for example, history of circle count, battery health and max battery capacity in order to track the benefits of using AlDente, history of charge/discharge periods, ...
Thanks

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Just letting you know that we are closing this repository since we continued using the original AlDente repository: https://github.com/davidwernhart/AlDente-Charge-Limiter
However, we have not forgotten about your feature request and we have this thread open about it: https://github.com/davidwernhart/AlDente-Charge-Limiter/issues/250

Cheers,
Matthias
